//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ClientDataMapModel", "FK_ClientAddress_AddressType_AddressTypeCode", "AddressType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientLocate.Tests.AddressType), "ClientAddress", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientLocate.Tests.ClientAddress), true)]
[assembly: EdmRelationshipAttribute("ClientDataMapModel", "FK_ClientAddress_ClientInfo_ClientId", "ClientInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientLocate.Tests.ClientInfo), "ClientAddress", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientLocate.Tests.ClientAddress), true)]
[assembly: EdmRelationshipAttribute("ClientDataMapModel", "FK_Phone_ClientInfo_ClientId", "ClientInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientLocate.Tests.ClientInfo), "Phone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientLocate.Tests.Phone), true)]
[assembly: EdmRelationshipAttribute("ClientDataMapModel", "FK_Phone_PhoneType_PhoneTypeCode", "PhoneType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ClientLocate.Tests.PhoneType), "Phone", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ClientLocate.Tests.Phone), true)]

#endregion

namespace ClientLocate.Tests
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ClientDBContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ClientDBContext object using the connection string found in the 'ClientDBContext' section of the application configuration file.
        /// </summary>
        public ClientDBContext() : base("name=ClientDBContext", "ClientDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClientDBContext object.
        /// </summary>
        public ClientDBContext(string connectionString) : base(connectionString, "ClientDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClientDBContext object.
        /// </summary>
        public ClientDBContext(EntityConnection connection) : base(connection, "ClientDBContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClientAddress> ClientAddresses
        {
            get
            {
                if ((_ClientAddresses == null))
                {
                    _ClientAddresses = base.CreateObjectSet<ClientAddress>("ClientAddresses");
                }
                return _ClientAddresses;
            }
        }
        private ObjectSet<ClientAddress> _ClientAddresses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClientInfo> ClientInfoes
        {
            get
            {
                if ((_ClientInfoes == null))
                {
                    _ClientInfoes = base.CreateObjectSet<ClientInfo>("ClientInfoes");
                }
                return _ClientInfoes;
            }
        }
        private ObjectSet<ClientInfo> _ClientInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Phone> Phones
        {
            get
            {
                if ((_Phones == null))
                {
                    _Phones = base.CreateObjectSet<Phone>("Phones");
                }
                return _Phones;
            }
        }
        private ObjectSet<Phone> _Phones;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AddressType> AddressTypes
        {
            get
            {
                if ((_AddressTypes == null))
                {
                    _AddressTypes = base.CreateObjectSet<AddressType>("AddressTypes");
                }
                return _AddressTypes;
            }
        }
        private ObjectSet<AddressType> _AddressTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhoneType> PhoneTypes
        {
            get
            {
                if ((_PhoneTypes == null))
                {
                    _PhoneTypes = base.CreateObjectSet<PhoneType>("PhoneTypes");
                }
                return _PhoneTypes;
            }
        }
        private ObjectSet<PhoneType> _PhoneTypes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClientAddresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientAddresses(ClientAddress clientAddress)
        {
            base.AddObject("ClientAddresses", clientAddress);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClientInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientInfoes(ClientInfo clientInfo)
        {
            base.AddObject("ClientInfoes", clientInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Phones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhones(Phone phone)
        {
            base.AddObject("Phones", phone);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AddressTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAddressTypes(AddressType addressType)
        {
            base.AddObject("AddressTypes", addressType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhoneTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhoneTypes(PhoneType phoneType)
        {
            base.AddObject("PhoneTypes", phoneType);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientDataMapModel", Name="AddressType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AddressType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AddressType object.
        /// </summary>
        /// <param name="addressTypeCode">Initial value of the AddressTypeCode property.</param>
        /// <param name="lastModifiedBy">Initial value of the LastModifiedBy property.</param>
        /// <param name="lastModifiedDate">Initial value of the LastModifiedDate property.</param>
        public static AddressType CreateAddressType(global::System.String addressTypeCode, global::System.String lastModifiedBy, global::System.DateTime lastModifiedDate)
        {
            AddressType addressType = new AddressType();
            addressType.AddressTypeCode = addressTypeCode;
            addressType.LastModifiedBy = lastModifiedBy;
            addressType.LastModifiedDate = lastModifiedDate;
            return addressType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddressTypeCode
        {
            get
            {
                return _AddressTypeCode;
            }
            set
            {
                if (_AddressTypeCode != value)
                {
                    OnAddressTypeCodeChanging(value);
                    ReportPropertyChanging("AddressTypeCode");
                    _AddressTypeCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AddressTypeCode");
                    OnAddressTypeCodeChanged();
                }
            }
        }
        private global::System.String _AddressTypeCode;
        partial void OnAddressTypeCodeChanging(global::System.String value);
        partial void OnAddressTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private global::System.String _LastModifiedBy;
        partial void OnLastModifiedByChanging(global::System.String value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModifiedDate
        {
            get
            {
                return _LastModifiedDate;
            }
            set
            {
                OnLastModifiedDateChanging(value);
                ReportPropertyChanging("LastModifiedDate");
                _LastModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedDate");
                OnLastModifiedDateChanged();
            }
        }
        private global::System.DateTime _LastModifiedDate;
        partial void OnLastModifiedDateChanging(global::System.DateTime value);
        partial void OnLastModifiedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientDataMapModel", "FK_ClientAddress_AddressType_AddressTypeCode", "ClientAddress")]
        public EntityCollection<ClientAddress> ClientAddresses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClientAddress>("ClientDataMapModel.FK_ClientAddress_AddressType_AddressTypeCode", "ClientAddress");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClientAddress>("ClientDataMapModel.FK_ClientAddress_AddressType_AddressTypeCode", "ClientAddress", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientDataMapModel", Name="ClientAddress")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClientAddress : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClientAddress object.
        /// </summary>
        /// <param name="addressId">Initial value of the AddressId property.</param>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="addressSeqNum">Initial value of the AddressSeqNum property.</param>
        /// <param name="addressTypeCode">Initial value of the AddressTypeCode property.</param>
        /// <param name="formatCode">Initial value of the FormatCode property.</param>
        /// <param name="effectiveDate">Initial value of the EffectiveDate property.</param>
        /// <param name="expirationDate">Initial value of the ExpirationDate property.</param>
        /// <param name="lastModifiedBy">Initial value of the LastModifiedBy property.</param>
        /// <param name="lastModifiedDate">Initial value of the LastModifiedDate property.</param>
        public static ClientAddress CreateClientAddress(global::System.Int32 addressId, global::System.Int32 clientId, global::System.Int32 addressSeqNum, global::System.String addressTypeCode, global::System.String formatCode, global::System.DateTime effectiveDate, global::System.DateTime expirationDate, global::System.String lastModifiedBy, global::System.DateTime lastModifiedDate)
        {
            ClientAddress clientAddress = new ClientAddress();
            clientAddress.AddressId = addressId;
            clientAddress.ClientId = clientId;
            clientAddress.AddressSeqNum = addressSeqNum;
            clientAddress.AddressTypeCode = addressTypeCode;
            clientAddress.FormatCode = formatCode;
            clientAddress.EffectiveDate = effectiveDate;
            clientAddress.ExpirationDate = expirationDate;
            clientAddress.LastModifiedBy = lastModifiedBy;
            clientAddress.LastModifiedDate = lastModifiedDate;
            return clientAddress;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddressId
        {
            get
            {
                return _AddressId;
            }
            set
            {
                if (_AddressId != value)
                {
                    OnAddressIdChanging(value);
                    ReportPropertyChanging("AddressId");
                    _AddressId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AddressId");
                    OnAddressIdChanged();
                }
            }
        }
        private global::System.Int32 _AddressId;
        partial void OnAddressIdChanging(global::System.Int32 value);
        partial void OnAddressIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OasisAddressId
        {
            get
            {
                return _OasisAddressId;
            }
            set
            {
                OnOasisAddressIdChanging(value);
                ReportPropertyChanging("OasisAddressId");
                _OasisAddressId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OasisAddressId");
                OnOasisAddressIdChanged();
            }
        }
        private global::System.String _OasisAddressId;
        partial void OnOasisAddressIdChanging(global::System.String value);
        partial void OnOasisAddressIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                OnClientIdChanging(value);
                ReportPropertyChanging("ClientId");
                _ClientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientId");
                OnClientIdChanged();
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AddressSeqNum
        {
            get
            {
                return _AddressSeqNum;
            }
            set
            {
                OnAddressSeqNumChanging(value);
                ReportPropertyChanging("AddressSeqNum");
                _AddressSeqNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddressSeqNum");
                OnAddressSeqNumChanged();
            }
        }
        private global::System.Int32 _AddressSeqNum;
        partial void OnAddressSeqNumChanging(global::System.Int32 value);
        partial void OnAddressSeqNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddressTypeCode
        {
            get
            {
                return _AddressTypeCode;
            }
            set
            {
                OnAddressTypeCodeChanging(value);
                ReportPropertyChanging("AddressTypeCode");
                _AddressTypeCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddressTypeCode");
                OnAddressTypeCodeChanged();
            }
        }
        private global::System.String _AddressTypeCode;
        partial void OnAddressTypeCodeChanging(global::System.String value);
        partial void OnAddressTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FormatCode
        {
            get
            {
                return _FormatCode;
            }
            set
            {
                OnFormatCodeChanging(value);
                ReportPropertyChanging("FormatCode");
                _FormatCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FormatCode");
                OnFormatCodeChanged();
            }
        }
        private global::System.String _FormatCode;
        partial void OnFormatCodeChanging(global::System.String value);
        partial void OnFormatCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CassCode
        {
            get
            {
                return _CassCode;
            }
            set
            {
                OnCassCodeChanging(value);
                ReportPropertyChanging("CassCode");
                _CassCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CassCode");
                OnCassCodeChanged();
            }
        }
        private global::System.String _CassCode;
        partial void OnCassCodeChanging(global::System.String value);
        partial void OnCassCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EffectiveDate
        {
            get
            {
                return _EffectiveDate;
            }
            set
            {
                OnEffectiveDateChanging(value);
                ReportPropertyChanging("EffectiveDate");
                _EffectiveDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EffectiveDate");
                OnEffectiveDateChanged();
            }
        }
        private global::System.DateTime _EffectiveDate;
        partial void OnEffectiveDateChanging(global::System.DateTime value);
        partial void OnEffectiveDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpirationDate
        {
            get
            {
                return _ExpirationDate;
            }
            set
            {
                OnExpirationDateChanging(value);
                ReportPropertyChanging("ExpirationDate");
                _ExpirationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpirationDate");
                OnExpirationDateChanged();
            }
        }
        private global::System.DateTime _ExpirationDate;
        partial void OnExpirationDateChanging(global::System.DateTime value);
        partial void OnExpirationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Line1
        {
            get
            {
                return _Line1;
            }
            set
            {
                OnLine1Changing(value);
                ReportPropertyChanging("Line1");
                _Line1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Line1");
                OnLine1Changed();
            }
        }
        private global::System.String _Line1;
        partial void OnLine1Changing(global::System.String value);
        partial void OnLine1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Line2
        {
            get
            {
                return _Line2;
            }
            set
            {
                OnLine2Changing(value);
                ReportPropertyChanging("Line2");
                _Line2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Line2");
                OnLine2Changed();
            }
        }
        private global::System.String _Line2;
        partial void OnLine2Changing(global::System.String value);
        partial void OnLine2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CityName
        {
            get
            {
                return _CityName;
            }
            set
            {
                OnCityNameChanging(value);
                ReportPropertyChanging("CityName");
                _CityName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CityName");
                OnCityNameChanged();
            }
        }
        private global::System.String _CityName;
        partial void OnCityNameChanging(global::System.String value);
        partial void OnCityNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateCode
        {
            get
            {
                return _StateCode;
            }
            set
            {
                OnStateCodeChanging(value);
                ReportPropertyChanging("StateCode");
                _StateCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StateCode");
                OnStateCodeChanged();
            }
        }
        private global::System.String _StateCode;
        partial void OnStateCodeChanging(global::System.String value);
        partial void OnStateCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountryCode
        {
            get
            {
                return _CountryCode;
            }
            set
            {
                OnCountryCodeChanging(value);
                ReportPropertyChanging("CountryCode");
                _CountryCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CountryCode");
                OnCountryCodeChanged();
            }
        }
        private global::System.String _CountryCode;
        partial void OnCountryCodeChanging(global::System.String value);
        partial void OnCountryCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeliveryPointBarcode
        {
            get
            {
                return _DeliveryPointBarcode;
            }
            set
            {
                OnDeliveryPointBarcodeChanging(value);
                ReportPropertyChanging("DeliveryPointBarcode");
                _DeliveryPointBarcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeliveryPointBarcode");
                OnDeliveryPointBarcodeChanged();
            }
        }
        private global::System.String _DeliveryPointBarcode;
        partial void OnDeliveryPointBarcodeChanging(global::System.String value);
        partial void OnDeliveryPointBarcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GeographicalPrecisionCode
        {
            get
            {
                return _GeographicalPrecisionCode;
            }
            set
            {
                OnGeographicalPrecisionCodeChanging(value);
                ReportPropertyChanging("GeographicalPrecisionCode");
                _GeographicalPrecisionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GeographicalPrecisionCode");
                OnGeographicalPrecisionCodeChanged();
            }
        }
        private global::System.String _GeographicalPrecisionCode;
        partial void OnGeographicalPrecisionCodeChanging(global::System.String value);
        partial void OnGeographicalPrecisionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccuracyCode
        {
            get
            {
                return _AccuracyCode;
            }
            set
            {
                OnAccuracyCodeChanging(value);
                ReportPropertyChanging("AccuracyCode");
                _AccuracyCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccuracyCode");
                OnAccuracyCodeChanged();
            }
        }
        private global::System.String _AccuracyCode;
        partial void OnAccuracyCodeChanging(global::System.String value);
        partial void OnAccuracyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TerminalId
        {
            get
            {
                return _TerminalId;
            }
            set
            {
                OnTerminalIdChanging(value);
                ReportPropertyChanging("TerminalId");
                _TerminalId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TerminalId");
                OnTerminalIdChanged();
            }
        }
        private global::System.String _TerminalId;
        partial void OnTerminalIdChanging(global::System.String value);
        partial void OnTerminalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TechnicalObjectKey
        {
            get
            {
                return _TechnicalObjectKey;
            }
            set
            {
                OnTechnicalObjectKeyChanging(value);
                ReportPropertyChanging("TechnicalObjectKey");
                _TechnicalObjectKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TechnicalObjectKey");
                OnTechnicalObjectKeyChanged();
            }
        }
        private global::System.String _TechnicalObjectKey;
        partial void OnTechnicalObjectKeyChanging(global::System.String value);
        partial void OnTechnicalObjectKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private global::System.String _LastModifiedBy;
        partial void OnLastModifiedByChanging(global::System.String value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModifiedDate
        {
            get
            {
                return _LastModifiedDate;
            }
            set
            {
                OnLastModifiedDateChanging(value);
                ReportPropertyChanging("LastModifiedDate");
                _LastModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedDate");
                OnLastModifiedDateChanged();
            }
        }
        private global::System.DateTime _LastModifiedDate;
        partial void OnLastModifiedDateChanging(global::System.DateTime value);
        partial void OnLastModifiedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientDataMapModel", "FK_ClientAddress_AddressType_AddressTypeCode", "AddressType")]
        public AddressType AddressType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AddressType>("ClientDataMapModel.FK_ClientAddress_AddressType_AddressTypeCode", "AddressType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AddressType>("ClientDataMapModel.FK_ClientAddress_AddressType_AddressTypeCode", "AddressType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AddressType> AddressTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AddressType>("ClientDataMapModel.FK_ClientAddress_AddressType_AddressTypeCode", "AddressType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AddressType>("ClientDataMapModel.FK_ClientAddress_AddressType_AddressTypeCode", "AddressType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientDataMapModel", "FK_ClientAddress_ClientInfo_ClientId", "ClientInfo")]
        public ClientInfo ClientInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientInfo>("ClientDataMapModel.FK_ClientAddress_ClientInfo_ClientId", "ClientInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientInfo>("ClientDataMapModel.FK_ClientAddress_ClientInfo_ClientId", "ClientInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ClientInfo> ClientInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientInfo>("ClientDataMapModel.FK_ClientAddress_ClientInfo_ClientId", "ClientInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ClientInfo>("ClientDataMapModel.FK_ClientAddress_ClientInfo_ClientId", "ClientInfo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientDataMapModel", Name="ClientInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClientInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClientInfo object.
        /// </summary>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="oasisClientId">Initial value of the OasisClientId property.</param>
        /// <param name="effectiveDate">Initial value of the EffectiveDate property.</param>
        /// <param name="expirationDate">Initial value of the ExpirationDate property.</param>
        /// <param name="lastModifiedBy">Initial value of the LastModifiedBy property.</param>
        /// <param name="lastModifiedDate">Initial value of the LastModifiedDate property.</param>
        public static ClientInfo CreateClientInfo(global::System.Int32 clientId, global::System.String oasisClientId, global::System.DateTime effectiveDate, global::System.DateTime expirationDate, global::System.String lastModifiedBy, global::System.DateTime lastModifiedDate)
        {
            ClientInfo clientInfo = new ClientInfo();
            clientInfo.ClientId = clientId;
            clientInfo.OasisClientId = oasisClientId;
            clientInfo.EffectiveDate = effectiveDate;
            clientInfo.ExpirationDate = expirationDate;
            clientInfo.LastModifiedBy = lastModifiedBy;
            clientInfo.LastModifiedDate = lastModifiedDate;
            return clientInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                if (_ClientId != value)
                {
                    OnClientIdChanging(value);
                    ReportPropertyChanging("ClientId");
                    _ClientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClientId");
                    OnClientIdChanged();
                }
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OasisClientId
        {
            get
            {
                return _OasisClientId;
            }
            set
            {
                OnOasisClientIdChanging(value);
                ReportPropertyChanging("OasisClientId");
                _OasisClientId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OasisClientId");
                OnOasisClientIdChanged();
            }
        }
        private global::System.String _OasisClientId;
        partial void OnOasisClientIdChanging(global::System.String value);
        partial void OnOasisClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EffectiveDate
        {
            get
            {
                return _EffectiveDate;
            }
            set
            {
                OnEffectiveDateChanging(value);
                ReportPropertyChanging("EffectiveDate");
                _EffectiveDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EffectiveDate");
                OnEffectiveDateChanged();
            }
        }
        private global::System.DateTime _EffectiveDate;
        partial void OnEffectiveDateChanging(global::System.DateTime value);
        partial void OnEffectiveDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrimarySubtypeCode
        {
            get
            {
                return _PrimarySubtypeCode;
            }
            set
            {
                OnPrimarySubtypeCodeChanging(value);
                ReportPropertyChanging("PrimarySubtypeCode");
                _PrimarySubtypeCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrimarySubtypeCode");
                OnPrimarySubtypeCodeChanged();
            }
        }
        private global::System.String _PrimarySubtypeCode;
        partial void OnPrimarySubtypeCodeChanging(global::System.String value);
        partial void OnPrimarySubtypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NamePrefixCode
        {
            get
            {
                return _NamePrefixCode;
            }
            set
            {
                OnNamePrefixCodeChanging(value);
                ReportPropertyChanging("NamePrefixCode");
                _NamePrefixCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NamePrefixCode");
                OnNamePrefixCodeChanged();
            }
        }
        private global::System.String _NamePrefixCode;
        partial void OnNamePrefixCodeChanging(global::System.String value);
        partial void OnNamePrefixCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NameSuffixCode
        {
            get
            {
                return _NameSuffixCode;
            }
            set
            {
                OnNameSuffixCodeChanging(value);
                ReportPropertyChanging("NameSuffixCode");
                _NameSuffixCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NameSuffixCode");
                OnNameSuffixCodeChanged();
            }
        }
        private global::System.String _NameSuffixCode;
        partial void OnNameSuffixCodeChanging(global::System.String value);
        partial void OnNameSuffixCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LegalEntityCode
        {
            get
            {
                return _LegalEntityCode;
            }
            set
            {
                OnLegalEntityCodeChanging(value);
                ReportPropertyChanging("LegalEntityCode");
                _LegalEntityCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LegalEntityCode");
                OnLegalEntityCodeChanged();
            }
        }
        private global::System.String _LegalEntityCode;
        partial void OnLegalEntityCodeChanging(global::System.String value);
        partial void OnLegalEntityCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OriginalInceptionDate
        {
            get
            {
                return _OriginalInceptionDate;
            }
            set
            {
                OnOriginalInceptionDateChanging(value);
                ReportPropertyChanging("OriginalInceptionDate");
                _OriginalInceptionDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OriginalInceptionDate");
                OnOriginalInceptionDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OriginalInceptionDate;
        partial void OnOriginalInceptionDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOriginalInceptionDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IndividualDateOfBirth
        {
            get
            {
                return _IndividualDateOfBirth;
            }
            set
            {
                OnIndividualDateOfBirthChanging(value);
                ReportPropertyChanging("IndividualDateOfBirth");
                _IndividualDateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IndividualDateOfBirth");
                OnIndividualDateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _IndividualDateOfBirth;
        partial void OnIndividualDateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnIndividualDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrimaryLanguageCode
        {
            get
            {
                return _PrimaryLanguageCode;
            }
            set
            {
                OnPrimaryLanguageCodeChanging(value);
                ReportPropertyChanging("PrimaryLanguageCode");
                _PrimaryLanguageCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrimaryLanguageCode");
                OnPrimaryLanguageCodeChanged();
            }
        }
        private global::System.String _PrimaryLanguageCode;
        partial void OnPrimaryLanguageCodeChanging(global::System.String value);
        partial void OnPrimaryLanguageCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TerminalId
        {
            get
            {
                return _TerminalId;
            }
            set
            {
                OnTerminalIdChanging(value);
                ReportPropertyChanging("TerminalId");
                _TerminalId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TerminalId");
                OnTerminalIdChanged();
            }
        }
        private global::System.String _TerminalId;
        partial void OnTerminalIdChanging(global::System.String value);
        partial void OnTerminalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpirationDate
        {
            get
            {
                return _ExpirationDate;
            }
            set
            {
                OnExpirationDateChanging(value);
                ReportPropertyChanging("ExpirationDate");
                _ExpirationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpirationDate");
                OnExpirationDateChanged();
            }
        }
        private global::System.DateTime _ExpirationDate;
        partial void OnExpirationDateChanging(global::System.DateTime value);
        partial void OnExpirationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatutoryTitleCode
        {
            get
            {
                return _StatutoryTitleCode;
            }
            set
            {
                OnStatutoryTitleCodeChanging(value);
                ReportPropertyChanging("StatutoryTitleCode");
                _StatutoryTitleCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StatutoryTitleCode");
                OnStatutoryTitleCodeChanged();
            }
        }
        private global::System.String _StatutoryTitleCode;
        partial void OnStatutoryTitleCodeChanging(global::System.String value);
        partial void OnStatutoryTitleCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CanSendMarketingMaterials
        {
            get
            {
                return _CanSendMarketingMaterials;
            }
            set
            {
                OnCanSendMarketingMaterialsChanging(value);
                ReportPropertyChanging("CanSendMarketingMaterials");
                _CanSendMarketingMaterials = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CanSendMarketingMaterials");
                OnCanSendMarketingMaterialsChanged();
            }
        }
        private Nullable<global::System.Boolean> _CanSendMarketingMaterials;
        partial void OnCanSendMarketingMaterialsChanging(Nullable<global::System.Boolean> value);
        partial void OnCanSendMarketingMaterialsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsClientBirthDateEstimated
        {
            get
            {
                return _IsClientBirthDateEstimated;
            }
            set
            {
                OnIsClientBirthDateEstimatedChanging(value);
                ReportPropertyChanging("IsClientBirthDateEstimated");
                _IsClientBirthDateEstimated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsClientBirthDateEstimated");
                OnIsClientBirthDateEstimatedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsClientBirthDateEstimated;
        partial void OnIsClientBirthDateEstimatedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsClientBirthDateEstimatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsAutoORCycleCustomer
        {
            get
            {
                return _IsAutoORCycleCustomer;
            }
            set
            {
                OnIsAutoORCycleCustomerChanging(value);
                ReportPropertyChanging("IsAutoORCycleCustomer");
                _IsAutoORCycleCustomer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAutoORCycleCustomer");
                OnIsAutoORCycleCustomerChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsAutoORCycleCustomer;
        partial void OnIsAutoORCycleCustomerChanging(Nullable<global::System.Boolean> value);
        partial void OnIsAutoORCycleCustomerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsClaimantRelationshipExists
        {
            get
            {
                return _IsClaimantRelationshipExists;
            }
            set
            {
                OnIsClaimantRelationshipExistsChanging(value);
                ReportPropertyChanging("IsClaimantRelationshipExists");
                _IsClaimantRelationshipExists = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsClaimantRelationshipExists");
                OnIsClaimantRelationshipExistsChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsClaimantRelationshipExists;
        partial void OnIsClaimantRelationshipExistsChanging(Nullable<global::System.Boolean> value);
        partial void OnIsClaimantRelationshipExistsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private global::System.String _LastModifiedBy;
        partial void OnLastModifiedByChanging(global::System.String value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModifiedDate
        {
            get
            {
                return _LastModifiedDate;
            }
            set
            {
                OnLastModifiedDateChanging(value);
                ReportPropertyChanging("LastModifiedDate");
                _LastModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedDate");
                OnLastModifiedDateChanged();
            }
        }
        private global::System.DateTime _LastModifiedDate;
        partial void OnLastModifiedDateChanging(global::System.DateTime value);
        partial void OnLastModifiedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientDataMapModel", "FK_ClientAddress_ClientInfo_ClientId", "ClientAddress")]
        public EntityCollection<ClientAddress> ClientAddresses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClientAddress>("ClientDataMapModel.FK_ClientAddress_ClientInfo_ClientId", "ClientAddress");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClientAddress>("ClientDataMapModel.FK_ClientAddress_ClientInfo_ClientId", "ClientAddress", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientDataMapModel", "FK_Phone_ClientInfo_ClientId", "Phone")]
        public EntityCollection<Phone> Phones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Phone>("ClientDataMapModel.FK_Phone_ClientInfo_ClientId", "Phone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Phone>("ClientDataMapModel.FK_Phone_ClientInfo_ClientId", "Phone", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientDataMapModel", Name="Phone")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Phone : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Phone object.
        /// </summary>
        /// <param name="phoneId">Initial value of the PhoneId property.</param>
        /// <param name="clientId">Initial value of the ClientId property.</param>
        /// <param name="phoneSeqNum">Initial value of the PhoneSeqNum property.</param>
        /// <param name="effectiveDate">Initial value of the EffectiveDate property.</param>
        /// <param name="expirationDate">Initial value of the ExpirationDate property.</param>
        /// <param name="areaCode">Initial value of the AreaCode property.</param>
        /// <param name="phoneNumber">Initial value of the PhoneNumber property.</param>
        /// <param name="phoneTypeCode">Initial value of the PhoneTypeCode property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="terminalId">Initial value of the TerminalId property.</param>
        /// <param name="lastModifiedBy">Initial value of the LastModifiedBy property.</param>
        /// <param name="lastModifiedDate">Initial value of the LastModifiedDate property.</param>
        public static Phone CreatePhone(global::System.Int32 phoneId, global::System.Int32 clientId, global::System.Byte phoneSeqNum, global::System.DateTime effectiveDate, global::System.DateTime expirationDate, global::System.String areaCode, global::System.String phoneNumber, global::System.String phoneTypeCode, global::System.String userId, global::System.String terminalId, global::System.String lastModifiedBy, global::System.DateTime lastModifiedDate)
        {
            Phone phone = new Phone();
            phone.PhoneId = phoneId;
            phone.ClientId = clientId;
            phone.PhoneSeqNum = phoneSeqNum;
            phone.EffectiveDate = effectiveDate;
            phone.ExpirationDate = expirationDate;
            phone.AreaCode = areaCode;
            phone.PhoneNumber = phoneNumber;
            phone.PhoneTypeCode = phoneTypeCode;
            phone.UserId = userId;
            phone.TerminalId = terminalId;
            phone.LastModifiedBy = lastModifiedBy;
            phone.LastModifiedDate = lastModifiedDate;
            return phone;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PhoneId
        {
            get
            {
                return _PhoneId;
            }
            set
            {
                if (_PhoneId != value)
                {
                    OnPhoneIdChanging(value);
                    ReportPropertyChanging("PhoneId");
                    _PhoneId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PhoneId");
                    OnPhoneIdChanged();
                }
            }
        }
        private global::System.Int32 _PhoneId;
        partial void OnPhoneIdChanging(global::System.Int32 value);
        partial void OnPhoneIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientId
        {
            get
            {
                return _ClientId;
            }
            set
            {
                OnClientIdChanging(value);
                ReportPropertyChanging("ClientId");
                _ClientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientId");
                OnClientIdChanged();
            }
        }
        private global::System.Int32 _ClientId;
        partial void OnClientIdChanging(global::System.Int32 value);
        partial void OnClientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte PhoneSeqNum
        {
            get
            {
                return _PhoneSeqNum;
            }
            set
            {
                OnPhoneSeqNumChanging(value);
                ReportPropertyChanging("PhoneSeqNum");
                _PhoneSeqNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PhoneSeqNum");
                OnPhoneSeqNumChanged();
            }
        }
        private global::System.Byte _PhoneSeqNum;
        partial void OnPhoneSeqNumChanging(global::System.Byte value);
        partial void OnPhoneSeqNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EffectiveDate
        {
            get
            {
                return _EffectiveDate;
            }
            set
            {
                OnEffectiveDateChanging(value);
                ReportPropertyChanging("EffectiveDate");
                _EffectiveDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EffectiveDate");
                OnEffectiveDateChanged();
            }
        }
        private global::System.DateTime _EffectiveDate;
        partial void OnEffectiveDateChanging(global::System.DateTime value);
        partial void OnEffectiveDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExpirationDate
        {
            get
            {
                return _ExpirationDate;
            }
            set
            {
                OnExpirationDateChanging(value);
                ReportPropertyChanging("ExpirationDate");
                _ExpirationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpirationDate");
                OnExpirationDateChanged();
            }
        }
        private global::System.DateTime _ExpirationDate;
        partial void OnExpirationDateChanging(global::System.DateTime value);
        partial void OnExpirationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AreaCode
        {
            get
            {
                return _AreaCode;
            }
            set
            {
                OnAreaCodeChanging(value);
                ReportPropertyChanging("AreaCode");
                _AreaCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AreaCode");
                OnAreaCodeChanged();
            }
        }
        private global::System.String _AreaCode;
        partial void OnAreaCodeChanging(global::System.String value);
        partial void OnAreaCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extension
        {
            get
            {
                return _Extension;
            }
            set
            {
                OnExtensionChanging(value);
                ReportPropertyChanging("Extension");
                _Extension = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extension");
                OnExtensionChanged();
            }
        }
        private global::System.String _Extension;
        partial void OnExtensionChanging(global::System.String value);
        partial void OnExtensionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhoneTypeCode
        {
            get
            {
                return _PhoneTypeCode;
            }
            set
            {
                OnPhoneTypeCodeChanging(value);
                ReportPropertyChanging("PhoneTypeCode");
                _PhoneTypeCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PhoneTypeCode");
                OnPhoneTypeCodeChanged();
            }
        }
        private global::System.String _PhoneTypeCode;
        partial void OnPhoneTypeCodeChanging(global::System.String value);
        partial void OnPhoneTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.String _UserId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TerminalId
        {
            get
            {
                return _TerminalId;
            }
            set
            {
                OnTerminalIdChanging(value);
                ReportPropertyChanging("TerminalId");
                _TerminalId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TerminalId");
                OnTerminalIdChanged();
            }
        }
        private global::System.String _TerminalId;
        partial void OnTerminalIdChanging(global::System.String value);
        partial void OnTerminalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private global::System.String _LastModifiedBy;
        partial void OnLastModifiedByChanging(global::System.String value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModifiedDate
        {
            get
            {
                return _LastModifiedDate;
            }
            set
            {
                OnLastModifiedDateChanging(value);
                ReportPropertyChanging("LastModifiedDate");
                _LastModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedDate");
                OnLastModifiedDateChanged();
            }
        }
        private global::System.DateTime _LastModifiedDate;
        partial void OnLastModifiedDateChanging(global::System.DateTime value);
        partial void OnLastModifiedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientDataMapModel", "FK_Phone_ClientInfo_ClientId", "ClientInfo")]
        public ClientInfo ClientInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientInfo>("ClientDataMapModel.FK_Phone_ClientInfo_ClientId", "ClientInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientInfo>("ClientDataMapModel.FK_Phone_ClientInfo_ClientId", "ClientInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ClientInfo> ClientInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClientInfo>("ClientDataMapModel.FK_Phone_ClientInfo_ClientId", "ClientInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ClientInfo>("ClientDataMapModel.FK_Phone_ClientInfo_ClientId", "ClientInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientDataMapModel", "FK_Phone_PhoneType_PhoneTypeCode", "PhoneType")]
        public PhoneType PhoneType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneType>("ClientDataMapModel.FK_Phone_PhoneType_PhoneTypeCode", "PhoneType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneType>("ClientDataMapModel.FK_Phone_PhoneType_PhoneTypeCode", "PhoneType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PhoneType> PhoneTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhoneType>("ClientDataMapModel.FK_Phone_PhoneType_PhoneTypeCode", "PhoneType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PhoneType>("ClientDataMapModel.FK_Phone_PhoneType_PhoneTypeCode", "PhoneType", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ClientDataMapModel", Name="PhoneType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhoneType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhoneType object.
        /// </summary>
        /// <param name="phoneTypeCode">Initial value of the PhoneTypeCode property.</param>
        /// <param name="lastModifiedBy">Initial value of the LastModifiedBy property.</param>
        /// <param name="lastModifiedDate">Initial value of the LastModifiedDate property.</param>
        public static PhoneType CreatePhoneType(global::System.String phoneTypeCode, global::System.String lastModifiedBy, global::System.DateTime lastModifiedDate)
        {
            PhoneType phoneType = new PhoneType();
            phoneType.PhoneTypeCode = phoneTypeCode;
            phoneType.LastModifiedBy = lastModifiedBy;
            phoneType.LastModifiedDate = lastModifiedDate;
            return phoneType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhoneTypeCode
        {
            get
            {
                return _PhoneTypeCode;
            }
            set
            {
                if (_PhoneTypeCode != value)
                {
                    OnPhoneTypeCodeChanging(value);
                    ReportPropertyChanging("PhoneTypeCode");
                    _PhoneTypeCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PhoneTypeCode");
                    OnPhoneTypeCodeChanged();
                }
            }
        }
        private global::System.String _PhoneTypeCode;
        partial void OnPhoneTypeCodeChanging(global::System.String value);
        partial void OnPhoneTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastModifiedBy
        {
            get
            {
                return _LastModifiedBy;
            }
            set
            {
                OnLastModifiedByChanging(value);
                ReportPropertyChanging("LastModifiedBy");
                _LastModifiedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastModifiedBy");
                OnLastModifiedByChanged();
            }
        }
        private global::System.String _LastModifiedBy;
        partial void OnLastModifiedByChanging(global::System.String value);
        partial void OnLastModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastModifiedDate
        {
            get
            {
                return _LastModifiedDate;
            }
            set
            {
                OnLastModifiedDateChanging(value);
                ReportPropertyChanging("LastModifiedDate");
                _LastModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastModifiedDate");
                OnLastModifiedDateChanged();
            }
        }
        private global::System.DateTime _LastModifiedDate;
        partial void OnLastModifiedDateChanging(global::System.DateTime value);
        partial void OnLastModifiedDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ClientDataMapModel", "FK_Phone_PhoneType_PhoneTypeCode", "Phone")]
        public EntityCollection<Phone> Phones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Phone>("ClientDataMapModel.FK_Phone_PhoneType_PhoneTypeCode", "Phone");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Phone>("ClientDataMapModel.FK_Phone_PhoneType_PhoneTypeCode", "Phone", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
